export SQUAD_DIR=squad1.1
CUDA_VISIBLE_DEVICES=1 python run_squad-niu.py \
  --model_type mobilebert \
  --model_name_or_path results/layerdrop/L-6_H-512_A-8 \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file $SQUAD_DIR/train-v1.1.json \
  --predict_file $SQUAD_DIR/dev-v1.1.json \
  --max_seq_length 384 \
  --per_gpu_train_batch_size 1 \
  --per_gpu_eval_batch_size 1 \
  --max_answer_length 30 \
  --max_query_length 64 \
  --n_best_size=20 \
  --learning_rate 3e-5 \
  --num_train_epochs 5.0 \
  --overwrite_output_dir \
  --doc_stride 128 \
  --output_dir results/retrain_squad_output_mobilebert_jiexiong_onnx_scale_batch1 \
  --save_steps 10000
